In [90]:
from PIL import Image
import os,sys
import matplotlib.pyplot as plt
import numpy as np
import skimage
from pathlib import Path
from skimage.io import imread
from sklearn.utils import Bunch
from sklearn import svm,metrics,datasets
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.metrics import accuracy_score 
from sklearn.naive_bayes import GaussianNB 
from sklearn.svm import SVC 
from sklearn.preprocessing import StandardScaler
import pickle

In [92]:
def load_image(path):
        image_dir=Path(path)
        folders=[directory for directory in image_dir.iterdir() if directory.is_dir()]
        categories=[fo.name for fo in folders]
        images=[]
        flat_data=[]
        target=[]
        
        for i,direc in enumerate(folders):
            for file in direc.iterdir():
                img=imread(file)
                flat_data.append(img.flatten())
                images.append(img)
                target.append(i)
        flat_data=np.array(flat_data)
        target=np.array(target)
        images=np.array(images)
        return Bunch(data=flat_data,target=target,target_names=categories)

In [93]:
image_dataset=load_image(r'./hog_dataset')

In [94]:
image_dataset.target_names


['basal cell carcinoma', 'melanoma', 'naevus']

In [97]:
image_dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [98]:
x_train,x_test,y_train,y_test=train_test_split(image_dataset.data,image_dataset.target,test_size=0.1)

In [99]:
model=svm.SVC()
model.fit(x_train,y_train)
pickle.dump(model,open('./svm.pkl','wb'))
pred=model.predict(x_test)
pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2])

In [100]:
from sklearn.metrics import accuracy_score
print(accuracy_score(pred,y_test))

0.8235294117647058


In [103]:
from sklearn.naive_bayes import GaussianNB 

In [105]:
gnb = GaussianNB().fit(x_train, y_train) 
pickle.dump(gnb,open('./naive_bayes.pkl','wb'))
gnb_predictions = gnb.predict(x_test) 


In [106]:
print(accuracy_score(gnb_predictions,y_test))

0.8823529411764706


In [107]:
print(gnb_predictions)


[2 2 2 2 1 2 1 2 1 2 1 2 2 2 2 2 2]


In [108]:
print(y_test)

[2 2 2 2 2 2 1 2 1 2 2 2 2 2 2 2 2]


In [109]:
image_dataset=load_image(r'./hog_dataset')

In [110]:
# Evaluate the model
predictions = model.predict(x_test)
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.8235294117647058
